
name: Run R-script

on: push

jobs: 
  trigger_r: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1', '4.0.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@master # Checkouts and clones the last commit

      - name: Setup R
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{ matrix.R }}

      - name: Run R
        run: |

          ls -lah

          Rscript r_script.R

