
name: Run R-script

on: push

jobs: 
  trigger_r: 
    runs-on: ubuntu-latest
    steps:
      - name: Check versions
        run: |
          ls -lah

          Rscript r_script.R

          
      

